# Generated by Django 5.1 on 2024-11-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0002_loan_loan_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='end_date',
        ),
    ]
