# Generated by Django 5.1 on 2024-11-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0003_remove_loan_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='Loan_Duration',
            field=models.IntegerField(default='In Months'),
        ),
    ]
