# Generated by Django 5.1 on 2024-11-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0004_alter_loan_loan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='Loan_Duration',
            field=models.IntegerField(default=False, help_text='In months'),
        ),
    ]
