# Generated by Django 5.1 on 2024-11-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0005_alter_loan_loan_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='paid_date',
        ),
    ]
