# Generated by Django 5.1 on 2024-11-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0007_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CNIC',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Loan_Duration',
            field=models.IntegerField(default=12, help_text='In months'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
